# Generated by Django 4.1 on 2022-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fakultas', models.CharField(max_length=200)),
                ('prodi', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
