# Generated by Django 4.1 on 2022-10-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0002_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenaga_Pendidik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
    ]
