# Generated by Django 4.1 on 2022-10-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0004_dosen_photo_mahasiswa_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='alamat',
            new_name='jabatan',
        ),
        migrations.RenameField(
            model_name='tenaga_pendidik',
            old_name='alamat',
            new_name='jabatan',
        ),
    ]
